### ISSUE TITLE
unknown node of type "NumberLiteral" with constructor "Node" when using numbers for values

### ISSUE THREAD

**Issue by cly** [martinandert/babel-plugin-css-in-js#1]
`width: 80` used to work now it throws this error.

**Comment by martinandert** [comment]
Hi @cly, I cannot reproduce this. I tested with

```js
var styles = cssInJS({ 
  foo: { 
    width: 80 
  } 
});
```

which transforms to

```js
var styles = { 
  foo: "test-styles-foo"
};
```

and outputs
```css
.test-styles-foo {
  width: 80px;
}
```
This is all expected.

Maybe you're using an outdated version of Babel somewhere else. Babel's changelog states that `NumberLiteral` was renamed to `NumericLiteral` in version 6.0.18.

**Comment by cly** [comment]
Aha I'm on 6.0.15.. thanks for a breaking change babel and not doing semver properly -__-.

Cool, that's helps a lot.
