### ISSUE TITLE
Is there any support for sub-selectors currently?

### ISSUE THREAD

**Issue by dkwingsmt** [martinandert/babel-plugin-css-in-js#23]
Hello, I wonder if subselectors are supported at the moment, since either of following syntax seems to throw syntax errors,
```
// Either 
const classes = ({
  'wrapper title': {
    margin: 1,
  }
})

// Or
const classes = ({
  'wrapper': {
    'title': {
      margin: 1,
    }
  }
})
```

Despite the second syntax being a SASS style and might not be the focus of this project, the first syntax actually belongs to CSS syntax and is quite useful, or actually irreplaceably necessary, in practice.

**Comment by martinandert** [comment]
Hi @dkwingsmt,

your first syntax example should actually work.

Something like this:

```js
var styles = cssInJS({ 
  foo: { 
    marginTop: 10
  }, 
  'foo p': { 
    color: 'red' 
  } 
});
```

will get transformed to this:

```js
var styles = { 
  foo: 'test-foo', 
  foo p: 'test-foo p' 
};
```

an that CSS:

```css
.test-foo {
  margin-top: 10px;
}
.test-foo p {
  color: red;
}
```

**Comment by martinandert** [comment]
Oh wait! That `foo p' key in the transformed `styles` object actually *is* invalid syntax and throws a "SyntaxError: Unexpected identifier". Is that also the exception you are getting?

**Comment by dkwingsmt** [comment]
I think so. I do remember seeing an "Unexpected identifier" error in some cases, not clear if it was this one. Will check tomorrow if needed.

**Comment by martinandert** [comment]
> Will check tomorrow if needed.

Yeah, please do.

**Comment by dkwingsmt** [comment]
Yes, that's what I got.

**Comment by martinandert** [comment]
@dkwingsmt The syntax error got fixed in v1.4.1. So your first example above should now properly work. Please check.

I also plan to support for your second proposal (subselectors inside the class name spec) soon.

**Comment by dkwingsmt** [comment]
Wow that sounds like a great news. Thank you.

By the way, in your test case, `p` being not localized is a little unexpected to me. Well, it doesn't matter if you will implement my second proposal.

**Comment by martinandert** [comment]
> By the way, in your test case, `p` being not localized is a little unexpected to me.

What do you mean with "p being not localized"?

**Comment by dkwingsmt** [comment]
Never mind. I've tested it today and it really works well. Thank you, and looking forward to it. :)
