### ISSUE TITLE
Usage in a webpack dev environment

### ISSUE THREAD

**Issue by Nimaear** [martinandert/babel-plugin-css-in-js#4]
I am wondering how one would go about setting a webpack dev environment up with this plugin? All my efforts have so far ended up with the styles of the last saved file overwriting the content of the bundled file.

**Comment by martinandert** [comment]
It's hard to tell what's wrong with your environment from far away. Your dev setup might be misconfigured. I'd like to take a look at it in order to understand what's going on.

**Comment by Nimaear** [comment]
I stripped down the project as much as I could (There might be some orphan islands left in) and is available at : [https://github.com/Nimaear/bare-example].

You should be able to see the problem after ```npm install && npm run dev```

**Comment by Nimaear** [comment]
Created a pull request which solves the issue for me haven't encountered any problems so far.

**Comment by tokenvolt** [comment]
I'm having the same issue using webpack.

**Comment by martinandert** [comment]
I just released v1.2.2 with the referenced PR merged in.
