### ISSUE TITLE
Dynamic style objects

### ISSUE THREAD

**Issue by skitterm** [martinandert/babel-plugin-css-in-js#9]
I tried 
```javascript
var item = {
  color: 'red'
};
var styles = cssInJS({
  item: item
});
```
But I got the warning "Top level value must be an object expression".

I'm assuming that's what you mean in the caveats about not being able to do dynamic stuff in the stylesheet. Am I right? Is there any plan on adding dynamic functionality? It'd be great to use this if it did.

**Comment by martinandert** [comment]
> I'm assuming that's what you mean in the caveats about not being able to do dynamic stuff in the stylesheet. Am I right?

@skitterm Yes, that's correct. Babel only parses/transforms JS files, but it doesn't compile/interpret them.

As a workaround, you could use the `context` option (see the README on how to use it and also read the "Expressions in Style Rules" section). Maybe that helps?
